import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

//import './components/employeeComponent/style.css';
import './mern/style.css';

// importing bootstrap
import './../node_modules/bootstrap/dist/css/bootstrap.min.css';

// import App from './App';
// import the component to be mounted
// import FirstComponent from './components/firstComponent';
// import ParentComponent from "./components/propsstate/parentChild";
// import StateComponent from './components/propsstate/stateComponent';
//import EmployeeComponent from './components/employeeComponent/employeeComponent';
//import ValidationComponent from './components/validationComponent/validationComponent';
import MainComponent from './finalmern/mainComponent';
//import ListEmployees from './mern/listEmployees';
import LoginComponent from './finalmern/jwtClient';

import {BrowserRouter} from 'react-router-dom';


import reportWebVitals from './reportWebVitals';

// Mount the App component on the HTML element having 'id' as 'root'
// msg is the custom JSX attribute that will be generated by React.js JSX parser
// at runtime and the property 'message' will be passed to <FirstComponent/>
// the FirstComponent must accept it as the 'props'

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
    <MainComponent></MainComponent>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();